config_hash: b3142d4e
config_str: intersubject_reliability_fmridata_sub-07_sub-02
dataset:
  frame_rate: 4
  name: bold_moments
  path: /mnt/lustre/work/bethge/mwe467/datasets/bold_moments/ds005165/stimuli/stimulus_set/
  resolution: 256
feature_extraction:
  batch_size: 8
  layers:
  - encoder.conv1
  - encoder.layer1.0.conv2
  - encoder.layer2.0.conv2
  - encoder.layer3.0.conv2
  - encoder.layer4.0.conv2
  - encoder.compress1
  - encoder.groupnorm
  model: sub-07
  num_frames: 1
  num_workers: 8
feature_reduction:
  method: srp
  seed: 1234
fmri:
  apply_consistency_threshold: true
  intersubject:
    mode: pairwise
    source_sub_ids:
    - - sub-07
    target_sub_ids:
    - sub-02
  path: /mnt/lustre/work/bethge/mwe467/datasets/bold_moments/ds005165/derivatives/versionB/fsLR32k/GLM/
  roi_names:
  - V1
  - V2
  - V3
  - V4
  - V3A
  - V3B
  - V6
  - V6A
  - V7
  - V8
  - FFC
  - PIT
  - IPS1
  - MST
  - MT
  - FST
  - LO1
  - LO2
  - LO3
  - V7
  - IP0
  - IP1
  - MIP
  - VIP
  - LIPd
  - LIPv
  - AIP
  - 7Pm
  - 7PL
  - 7PC
  - 7Am
  - 7AL
  - VVC
  - VMV2
  - VMV3
  - VMV1
  - PHA2
  - PHA3
  - PH
  sub_id:
  - sub-07
  - sub-02
  voxel_consistency_threshold: 0.2
linear_predictivity:
  enabled: true
output_dir: output/b3142d4e
overwrite: true
procrustes:
  enabled: false
  feature_reduction_method: pca
  feature_reduction_seed: 1234
  frame_merge_strategy: average
  n_components: 64
  normalize_features: false
  score_function: frobenius
  use_cv_ankhsoni_prokrustes: false
rsa:
  dist_type: pearson
  enabled: true
  visualize_rdms: true
versa:
  dist_type: pearson
  enabled: false
  voxel_encoding:
    method: ridge
    one_alpha_per_voxel: false
    params:
      alphas:
      - 100.0
      - 1000.0
      - 10000.0
      - 100000.0
      - 1000000.0
      - 10000000.0
      cv: 5
      fit_intercept: true
      scoring: pearson
