[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"


[project]
name = "multitasking"
description = "Pipeline for evaluating models on brain alignment"
authors = [
  { name="Matthias Tangemann"},
  { name="Lotta Piefke"},
  { name="Larissa Höfling"},
  { name="Susanne Keller"}
]
readme = "README.md"
version = "1.0.0"
requires-python = ">=3.10"
dynamic = ["dependencies", "optional-dependencies"]


[tool.ruff]
lint.select = ["B", "D", "E", "W", "F", "FIX", "I", "T20"]
lint.ignore = ["D100", "D101", "D102", "D103", "D104", "D105", "D107", "E501"]
lint.pydocstyle.convention = "google"
exclude = ["_extern", "multitasking/plot_creation/**", "multitasking/analyses/alignment_pattern.py"]


[tool.setuptools]
packages = ["multitasking"]


[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}


[tool.setuptools.dynamic.optional-dependencies]
dev = {file = ["requirements-dev.txt"]}
