dataset:
  path: /mnt/lustre/work/bethge/mtangemann/data/multitasking/jobs/3766c2d7-e3e4-4d34-8cca-98ab578a7728/output/
  resolution: 256
  frame_rate: 5

fmri:
  path: /mnt/lustre/work/bethge/bkr578/data/multitasking_objaverse/fmri/
  sub_id: sub-0001
  roi_names: [
    "V1", "MT", "Pir", "A1"
    #"FST", "LO1", "LO2", "LO3", "RSC",
  ]
  test_set:
    seed: 5298
    size: .5  # half the dataset
  normalize: True  # apply standard scaler to data if set to 1

feature_extraction:
  model: sub-0001
  layers:
    - V1
    - MT
    - Pir
    - A1
  shuffle: False  # only for debugging, shuffle sample ids